### PR TITLE
Fix use of negative strides in loop filters

### LINKED ISSUE #636: Account for negative strides
See https://github.com/memorysafety/rav1d/pull/588#discussion_r1425759037.

### PR DESCRIPTION
**Pull request by fbossen**
Fixes slice construction and offset computation when negative strides are used.
* Partly fixes #636

### CODE REVIEW

File: src/recon.rs [hunk 1]
```diff
@@ -4426,23 +4426,38 @@ pub(crate) unsafe fn rav1d_filter_sbrow_lr<BD: BitDepth>(
     let y = sby * f.sb_step * 4;
     let ss_ver = (f.cur.p.layout == Rav1dPixelLayout::I420) as c_int;
     let h = f.sr_cur.p.p.h + 127 & !127;
+    let pix_stride = f.sr_cur.p.stride.map(BD::pxstride);
```
Comment (kkysen) [inline src/recon.rs:4429]: Could we name this `pxstride` to be consistent with `BD::pxstride`.  `pix` sounds a little too much like pic IMO.

**Review by kkysen — APPROVED** [review]

File: src/recon.rs (hunk 1 above)
Comment (fbossen) [reply src/recon.rs]: done

**Review by kkysen — APPROVED** [review]
